survey_form/config/routes.rb
Rails.application.routes.draw do
  resources :surveys do
    get 'answers', on: :member
  end
  resources :participants
  resources :answers

end

survey_form/app/models/answer.rb
class Answer < ActiveRecord::Base
  has_many :selections
  has_many :participants, through: :selections
end

survey_form/app/models/participant.rb
class Participant < ActiveRecord::Base
	has_many :selections
	has_many :answers, through: :selections
  has_many :questions, through: :answers
end

survey_form/app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :survey
  has_many :answers
  has_many :participants, through: :answers

  accepts_nested_attributes_for :answers
end

survey_form/app/models/response.rb
class Response < ActiveRecord::Base
	belongs_to :answer
	belongs_to :user
	belongs_to :question
	
end

survey_form/app/models/selection.rb
class Selection < ActiveRecord::Base
	belongs_to :answer
	belongs_to :participant
	
end

survey_form/app/models/survey.rb
class Survey < ActiveRecord::Base
	has_many :questions

  accepts_nested_attributes_for :questions
end

survey_form/app/models/user.rb
class User < ActiveRecord::Base
	has_many :answers
	has_many :questions, :through => :answers

end

survey_form/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

survey_form/app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name)
    end
end

survey_form/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index

	end

	def create
		
	end
end

survey_form/app/controllers/results_controller.rb
class ResultsController < ApplicationController
end

survey_form/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :answers]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  def answers
    @participants = Participant.all
    @questions = @survey.questions.order(importance: :asc)
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  	@participants = Participant.all
    @questions = @survey.questions.order(importance: :asc)
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
    	params.require(:survey).permit(:name,
      :questions_attributes => [:id, :content,
        :answers_attributes => [:id, :content, :participant_id]
      ])
  	end
end

survey_form/app/helpers/application_helper.rb
module ApplicationHelper
end

survey_form/app/helpers/participants_helper.rb
module ParticipantsHelper
end

survey_form/app/helpers/questions_helper.rb
module QuestionsHelper
end

survey_form/app/helpers/results_helper.rb
module ResultsHelper
end

survey_form/app/helpers/survey_helper.rb
module SurveyHelper
end

survey_form/app/helpers/surveys_helper.rb
module SurveysHelper
end

survey_form/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyForm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

survey_form/app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

survey_form/app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

survey_form/app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

survey_form/app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

survey_form/app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

survey_form/app/views/survey/index.html.erb
<h1>Survey</h1>
	
	<%= form_tag("/post", method: "post") do |f| %>
  

		
	<% @questions.each do |question| %>
		<h4> <%= question.importance %>. <%= question.content %> </h4>
		<% question.answers.each do |answer| %>
		<div>
		<%= radio_button :response, '#{answer.content}' %>

		<input type="radio"><%= answer.content %></div>

		<% end %>
	<% end %>
  <%= submit_tag("Submit") %>
<% end %>

survey_form/app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

survey_form/app/views/surveys/answers.html.erb
<h1><%= @survey.name %> Answers</h1>
testing answers here
<%= form_for(@survey) do |f| %>
  <% @participants.each do |participant| -%>
  <h3><%= participant.name %></h3>
  <table>
    <thead>
      <tr>
        <td>Questions</td>
        <td>Answer</td>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| -%>
      <tr>
        <td><%= question.content %></td>
        <td>
        <%= f.fields_for :questions, question do |q| -%>
          <%= q.fields_for :answers, question.answers.find_or_initialize_by(participant: participant) do |a| -%>
            <%= a.text_area :content %>
            <%= a.hidden_field :participant_id, participant.id %>
          <% end -%>
        <% end -%>
        </td>
      </tr>
      <% end -%>
    </tbody>
  </table>
  <% end -%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end -%>

survey_form/app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

survey_form/app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

survey_form/app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

survey_form/app/views/surveys/old-code.html.erb
	<% @questions.each do |question| %>
			<% button_type = question.question_type %>
			<h4> <%= question.importance %>. <%= question.content %> </h4>
			
			<% question.answers.each do |answer| %>
			<%= form_for(@question do |f| %>
				<div>
		  <%= f.button_type    %> 
		  <%= label answer.content %>
				</div>
			<% end %>
	<% end %>

<% end %>







<% @questions.each do |question| %>
<h4> <%= question.importance %>. <%= question.content %> </h4>
<%= form_for ([@question, @user.responses.build]) do |f| %>
  <p>
    <%= f.label @question.content %><br />
    
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

<% end %>


<%= form_for @user do |f| %>
	<% @questions.each do |question| %>
	<h4> <%= question.importance %>. <%= question.content %> </h4>

  <ul>
    <%= f.fields_for :addresses do |addresses_form| %>
      <li>
        <%= addresses_form.label :kind %>
        <%= addresses_form.text_field :kind %>
 
        <%= addresses_form.label :street %>
        <%= addresses_form.text_field :street %>
        ...
      </li>
      	<% end %>
    <% end %>
<% end %>




<%= form_for :survey do |form| %>
  <%= form.fields_for :question do |question_form| %>
   <%= question_form.text_field :question %>
  	<% end %>
  <%= form.fields_for :answers do |answer_form| %>
   <%= question_form.text_field :answer %>
  <% end %>
  <%= form.submit %>
<% end %>





<h1>Survey</h1>
	
	<%= form_tag("/post", method: "post") do |f| %>
  

		
	<% @questions.each do |question| %>
		<h4> <%= question.importance %>. <%= question.content %> </h4>
		<% question.answers.each do |answer| %>
		<div>
		<%= radio_button :response, '#{answer.content}' %>

		<input type="radio"><%= answer.content %></div>

		<% end %>
	<% end %>
  <%= submit_tag("Submit") %>
<% end %>

survey_form/app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @survey.name %>
</p>

<h1>Survey</h1>
	
	

		
	<% @questions.each do |question| %>
		<h4> <%= question.importance %>. <%= question.content %> </h4>
		<% question.answers.each do |answer| %>
		<div>

		<input type="radio"><%= answer.content %></div>

		<% end %>
	<% end %>
  <%= submit_tag("Submit") %>


<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>